export const localStorageKeys = {
  ACCESS_TOKEN: "ACCESS_TOKEN_SS",
  USER_DETAILS: "USER_DETAILS_SS",
  REFRESH_TOKEN: "USER_REFRESH_TOKEN_SS",
  VENDOR_ACCESS_TOKEN: "VENDOR_ACCESS_TOKEN_SS",
  VENDOR_USER_DETAILS: "VENDOR_USER_DETAILS_SS",
  VENDOR_REFRESH_TOKEN: "VENDOR_USER_REFRESH_TOKEN_SS"
};
